export const mockProducts = [
  {
    id: '1',
    name: 'Wireless Bluetooth Headphones',
    description: 'Premium noise-cancelling headphones with 30-hour battery life',
    price: 2999,
    images: ['https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=300&h=300&fit=crop'],
    category: 'Electronics',
    sellerId: 'seller1',
    inventory: 50,
    rating: 4.5,
    createdAt: new Date(),
  },
  {
    id: '2',
    name: 'Smart Fitness Watch',
    description: 'Track your health and fitness with this advanced smartwatch',
    price: 15999,
    images: ['https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=300&h=300&fit=crop'],
    category: 'Electronics',
    sellerId: 'seller2',
    inventory: 25,
    rating: 4.8,
    createdAt: new Date(),
  },
  {
    id: '3',
    name: 'Organic Cotton T-Shirt',
    description: 'Comfortable and sustainable cotton t-shirt',
    price: 799,
    images: ['https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=300&h=300&fit=crop'],
    category: 'Fashion',
    sellerId: 'seller3',
    inventory: 100,
    rating: 4.2,
    createdAt: new Date(),
  },
  {
    id: '4',
    name: 'Professional Camera',
    description: 'High-quality DSLR camera for photography enthusiasts',
    price: 45999,
    images: ['https://images.unsplash.com/photo-1606983340126-99ab4feaa64a?w=300&h=300&fit=crop'],
    category: 'Electronics',
    sellerId: 'seller4',
    inventory: 10,
    rating: 4.9,
    createdAt: new Date(),
  },
  {
    id: '5',
    name: 'Gaming Mechanical Keyboard',
    description: 'RGB backlit mechanical keyboard for gaming',
    price: 8999,
    images: ['https://images.unsplash.com/photo-1541140532154-b024d705b90a?w=300&h=300&fit=crop'],
    category: 'Electronics',
    sellerId: 'seller5',
    inventory: 30,
    rating: 4.6,
    createdAt: new Date(),
  },
  {
    id: '6',
    name: 'Yoga Mat Premium',
    description: 'Non-slip premium yoga mat for your daily practice',
    price: 1299,
    images: ['https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=300&h=300&fit=crop'],
    category: 'Sports',
    sellerId: 'seller6',
    inventory: 75,
    rating: 4.3,
    createdAt: new Date(),
  },
]

export const mockLiveSessions = [
  {
    id: 'live1',
    title: 'Tech Product Showcase',
    description: 'Latest gadgets and electronics',
    sellerId: 'seller1',
    isActive: true,
    viewerCount: 124,
  },
  {
    id: 'live2',
    title: 'Fashion Haul & Styling Tips',
    description: 'Summer collection preview',
    sellerId: 'seller3',
    isActive: true,
    viewerCount: 89,
  },
]